### ISSUE TITLE
feat: skip v-bind in <style> templates

### ISSUE THREAD

**Issue by Tahul** [nuxt-community/design-tokens-module#8]
I have a little question to ask you about Vue SFC compiler, and specifically about v-bind usage in <style> templates!

Working on the support for Design Tokens as a module for Nuxt, in the objective to add it in our stack as a styling + theming solution built for Nuxt themes.

For that purpose, I built a $dt() helper (referring to $designTokens()), that is globally available and type-safe, it gives an (almost) 0 runtime access to globally defined styling tokens CSS variables.

A typical usage would be:
```ts
// tokens.config.ts
import { palette } from '@nuxtjs/design-tokens'

export default defineTokens({
   colors: {
      // Generate colors shades tokens
      primary: palette('blue')
   }
})
```

```vue
// MyComponent.vue
<template>
   <div>
      Hello World!
   </div>
</template>

<style scoped>
div {
   color: v-bind($dt('colors.primary.500'));
}
</style>
```
 
Now that the whole context is here, here is what I'm trying to solve, replacing this:
```css
color: v-bind($dt('colors.primary.500'));
```

By:
```css
color: $dt('colors.primary.500');
 ```
 
Maybe by using a build step injected via the Nuxt module?

I would love to receive some help about this!

**Comment by antfu** [comment]
Yes, it would be possible to use a vite plugin (or unplugin also I guess) with `enfore: pre` to transform it before it get to Vue's compiler.

**Comment by Atinux** [comment]
Is this something you could look at @antfu ? 😊

**Comment by Tahul** [comment]
https://github.com/nuxt-community/design-tokens-module/blob/main/src/transform.ts

I think I managed to do it there, but I would love your review on the approach @antfu 🙏

Thank you so much for the suggestions!

**Comment by antfu** [comment]
The implementation looks good to me 👍

**Comment by Tahul** [comment]
I have a little question about transformers @antfu, do they work with SSR in development mode?

I can notice a little "blink" in these transformers, as if I do a fresh load of my page, I'll notice the code received by SSR in development won't contain the transformations?

No issues with production built website 😄
